---
abstract: ~
author:
  - 'Felix Ren-Chyan Chern (dryman) C<< <idryman@gmail.com> >>'
build_requires:
  ExtUtils::MakeMaker: 6.62
  Test::More: 0.42
configure_requires:
  ExtUtils::MakeMaker: 6.62
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.04'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-ZH-MMSEG
no_index:
  directory:
    - inc
    - t
requires:
  perl: 5.8.6
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.4005
